/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "tertiary-container": "#666868",
        "secondary-fixed-dim": "#c8c6c5",
        "outline": "#8d90a2",
        "on-surface-variant": "#c3c5d9",
        "on-secondary-fixed-variant": "#474646",
        "on-background": "#e1e1ef",
        "on-surface": "#e1e1ef",
        "on-secondary": "#313030",
        "surface-container": "#1d1f29",
        "primary-container": "#0055ff",
        "error-container": "#93000a",
        "surface-container-lowest": "#0c0e17",
        "error": "#ffb4ab",
        "on-primary-container": "#e3e6ff",
        "surface-container-low": "#191b25",
        "secondary-container": "#4a4949",
        "tertiary-fixed": "#e2e2e2",
        "primary-fixed-dim": "#b6c4ff",
        "outline-variant": "#434656",
        "background": "#11131c",
        "on-error-container": "#ffdad6",
        "on-primary-fixed": "#001551",
        "on-primary": "#002780",
        "inverse-on-surface": "#2e303a",
        "on-error": "#690005",
        "surface-variant": "#32343f",
        "surface-bright": "#373943",
        "surface": "#11131c",
        "secondary": "#c8c6c5",
        "primary": "#b6c4ff",
        "inverse-primary": "#004dea",
        "on-tertiary": "#2f3131",
        "surface-container-high": "#282933",
        "on-primary-fixed-variant": "#0039b3",
        "surface-container-highest": "#32343f",
        "secondary-fixed": "#e5e2e1",
        "on-tertiary-fixed-variant": "#454747",
        "on-tertiary-fixed": "#1a1c1c",
        "inverse-surface": "#e1e1ef",
        "surface-tint": "#b6c4ff",
        "primary-fixed": "#dce1ff",
        "on-tertiary-container": "#e7e7e7",
        "tertiary-fixed-dim": "#c6c6c7",
        "surface-dim": "#11131c",
        "tertiary": "#c6c6c7",
        "on-secondary-container": "#bab8b7",
        "on-secondary-fixed": "#1c1b1b"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "section-gap": "120px",
        "margin-desktop": "64px",
        "unit": "8px",
        "container-max": "1440px",
        "margin-mobile": "20px",
        "gutter": "24px"
      },
      "fontFamily": {
        "display-xl": ["Anton", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Anton", "sans-serif"],
        "headline-lg": ["Anton", "sans-serif"],
        "button-text": ["Geist", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Anton", "sans-serif"],
        "label-caps": ["Geist", "sans-serif"]
      },
      "fontSize": {
        "display-xl": ["96px", { "lineHeight": "100%", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "150%", "fontWeight": "400" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "110%", "fontWeight": "400" }],
        "headline-lg": ["48px", { "lineHeight": "110%", "letterSpacing": "0.02em", "fontWeight": "400" }],
        "button-text": ["14px", { "lineHeight": "100%", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "160%", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "120%", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "100%", "letterSpacing": "0.1em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
